---
title: "Food Explorer (Exercises to practice)"
output:
  html_document:
    toc: yes
date: "2023-05-14"
---

```{r setup, include=FALSE}
library(tidyverse)
``` 

```{r import_csv}
food_data <- read.csv("data/foodData.csv")
```

# 1. Which category of food has the highest average price?
```{r exercise1}

# group_by on "Category" and calculate average
group_categories <- food_data %>% 
                    group_by(Category) %>%
                    summarise(average = mean(Price))

# Sort by the highest mean price and get the first record
max_mean_price_category <- group_categories %>%
  arrange(desc(average)) %>%
  slice_head(n = 1)

max_mean_price_category
```

# 2. What is the most common country of origin for the food items?
```{r exercise2}
group_country <- food_data %>%
                 group_by(Country.of.Origin)  %>%
                  summarise(count = n())
                  
most_common_country_of_origin <- group_country %>%
                                  arrange(desc(count)) %>%
                                  slice_head(n = 1)

most_common_country_of_origin
```